apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextstep-web
  namespace: nextstep
  labels:
    app: nextstep-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextstep-web
  template:
    metadata:
      labels:
        app: nextstep-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101   # nginx default non-root user
      containers:
        - name: web
          image: gcr.io/nextstep-fiap-project/nextstep-web:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  # nginx writes cache/pid files
            capabilities:
              drop: ["ALL"]
              add: ["NET_BIND_SERVICE"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
