apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextstep-web
  labels:
    app: nextstep-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextstep-web
  template:
    metadata:
      labels:
        app: nextstep-web
    spec:
      containers:
        - name: web
          image: gcr.io/PROJECT_ID/nextstep-web:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
